<?php

namespace Ccta\AllianceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlliancePlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlliancePlayerRepository extends EntityRepository
{
}
