services:
    security.access.alliance_voter:
        class:    Ccta\AllianceBundle\Security\Authorization\Voter\AllianceVoter
        arguments: [@session]
        public:   false
        tags:
            - { name: security.voter }