ccta_user_admin_index:
    path: /admin/users
    defaults: { _controller: CctaUserBundle:Admin:index  }

ccta_user_admin_create:
    path: /admin/users/create
    defaults: { _controller: CctaUserBundle:Admin:create  }

ccta_user_admin_edit:
    path: /admin/users/edit/{id}
    defaults: { _controller: CctaUserBundle:Admin:edit  }
    requirements:
        id: \d+

ccta_user_admin_delete:
    path: /admin/users/delete/{id}
    defaults: { _controller: CctaUserBundle:Admin:delete  }
    requirements:
        id: \d+